metrics_stop_list = [
    'Transfers to bank account',
    'Failed transfers to bank account',
    'Disburse to Amazon Gift Card balance',
    'Charges to credit card',
    'Product, shipping and gift wrap taxes collected',
    'Product, shipping and gift wrap taxes refunded',
    'Amazon Obligated Tax Withheld',
    'Tax',
    'Transfers',
    'Net taxes collected on product sales and services',
    'Net deposits and withdrawals',
    'Net fees, including Amazon service fees, selling fees, FBA fees, shipping, and taxes',
    'Net sales, credits, and refunds'
]
metric_names = ['A-to-z Guarantee claims',
                'Adjustments',
                'Amazon Shipping Reimbursement',
                'Carrier shipping label adjustments',
                'Chargebacks',
                'Cost of Advertising',
                'Expenses',
                'FBA Liquidations proceeds adjustments',
                'FBA inventory and inbound services fees',
                'FBA inventory credit',
                'FBA liquidation proceeds',
                'FBA product sale refunds',
                'FBA product sales',
                'FBA selling fees',
                'FBA transaction fee refunds',
                'FBA transaction fees',
                'Gift wrap credit refunds',
                'Gift wrap credits',
                'Income',
                'Liquidations fees',
                'Other transaction fee refunds',
                'Other transaction fees',
                'Product sale refunds (non-FBA)',
                'Product sales (non-FBA)',
                'Promotional rebate refunds',
                'Promotional rebates',
                'Refund administration fees',
                'Refund for Advertiser',
                'SAFE-T reimbursement',
                'Seller fulfilled selling fees',
                'Selling fee refunds',
                'Service fees',
                'Shipping credit refunds',
                'Shipping credits',
                'Shipping label purchases',
                'Shipping label refunds'
                ]